package com.springboot.assetsphere.enums;

public enum JobTitle {

	ASSOCIATE_SOFTWARE_ENGINEER, SENIOR_SOFTWARE_ENGINEER, TECH_LEAD,PROJECT_MANAGER, HR_MANAGER, SYSTEM_ADMINISTRATOR,
    IT_SUPPORT_ENGINEER, NETWORK_ENGINEER, BUSINESS_ANALYST, INTERN
    
}
